### ISSUE TITLE
你好，ppqi inferenceModel 出现错误！

### ISSUE THREAD

**Issue by davidhefan** [jm12138/PaddleQuickInference#1]
File "/Applications/anaconda3/lib/python3.7/site-packages/ppqi/inference.py", line 22, in __init__
    self.config = self.load_config(modelpath, use_gpu, use_mkldnn)
  File "/Applications/anaconda3/lib/python3.7/site-packages/ppqi/inference.py", line 87, in load_config
    config.disable_gpu()
UnboundLocalError: local variable 'config' referenced before assignment

ppqi                               1.0.1
paddlepaddle                       2.0.0rc1

请问这个该如何解决呢？

**Comment by jm12138** [comment]
能贴一下相对完整的源代码吗？

**Comment by davidhefan** [comment]
`import numpy as np
from ppqi import InferenceModel


model = InferenceModel(
    modelpath='/Users/davidhe/Downloads/pd_model/inference_model',
    use_gpu=False,
    use_mkldnn=False
)
model.eval()`

错误信息如下：
Traceback (most recent call last):
  File "/Users/davidhe/PycharmProjects/hand_detection/model.py", line 8, in <module>
    use_mkldnn=False
  File "/Applications/anaconda3/lib/python3.7/site-packages/ppqi/inference.py", line 22, in __init__
    self.config = self.load_config(modelpath, use_gpu, use_mkldnn)
  File "/Applications/anaconda3/lib/python3.7/site-packages/ppqi/inference.py", line 87, in load_config
    config.disable_gpu()
UnboundLocalError: local variable 'config' referenced before assignment

就是按您示例的写法，直接就报错了，会是哪里的问题呢？

**Comment by jm12138** [comment]
应该是模型路径出问题了，麻烦发一下这个路径/Users/davidhe/Downloads/pd_model/inference_model下的文件名吗，截个图就行

**Comment by davidhefan** [comment]
上传图片显示不出来，目录下是如下2个文件：
```
__model__
__params__
```
这个有问题吗？

**Comment by jm12138** [comment]
模型没问题，应该就是python运行的时候没找到文件报的错，你可以先把路径换成 c://Users/davidhe/Downloads/pd_model/inference_model试试，我再排查一下代码看看有没有可能是啥子其他因素导致的

**Comment by davidhefan** [comment]
感谢，是我的路径问题。
这个错误提示把我整蒙了

**Comment by jm12138** [comment]
搞定了就行，目前版本已更新，添加了路径异常提示功能，也感谢你的反馈
